WashUSoccerFundraiser/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :plans
  get 'home/index'
  get 'home/show_team'
  post 'home/show_team'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'

  end

  root 'home#index'
end

WashUSoccerFundraiser/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

WashUSoccerFundraiser/app/models/plan.rb
class Plan < ApplicationRecord  
end

WashUSoccerFundraiser/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

WashUSoccerFundraiser/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

WashUSoccerFundraiser/app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
    def create
        @plan = Plan.find(params[:id])

        if @plan.nil?
            redirect_to root_path
            return 
        end
        
        #Set up stripe sesssion for payment
        @session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            line_items: [{
                name: @plan.name,
                description: @plan.description,
                amount: @plan.price_cents,
                currency: 'usd',
                quantity: 1,
            }],
            success_url: checkout_success_url,
            cancel_url: checkout_cancel_url
        )

        respond_to do |format|
            format.js # render create.js.erb
        end
    end

    def success
    end

    def cancel
        redirect_to root_path
    end
end

WashUSoccerFundraiser/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show_team
    @Plans = Plan.all
  end

  def show_players

  end
end

WashUSoccerFundraiser/app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plans = Plan.all
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:name, :description, :price_cents)
    end
end

WashUSoccerFundraiser/app/helpers/application_helper.rb
module ApplicationHelper
end

WashUSoccerFundraiser/app/helpers/checkout_helper.rb
module CheckoutHelper
end

WashUSoccerFundraiser/app/helpers/home_helper.rb
module HomeHelper
end

WashUSoccerFundraiser/app/helpers/plans_helper.rb
module PlansHelper
end

WashUSoccerFundraiser/app/views/checkout/create.js.erb
var stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
    sessionId: '<%= @session.id %>'
}).then(function (result) {
    console.log(result.error.message);
});

WashUSoccerFundraiser/app/views/checkout/success.html.erb
<h1>Success!</h1>

WashUSoccerFundraiser/app/views/home/index.html.erb
<!-- <%= javascript_pack_tag 'hello' %> -->

<h1>WashU Men's Soccer Covid19 Juggling Fundraiser</h1>

<div>
    <!--Progress Bar-->
</div>
<button>Share</button>
<%= button_to 'Sponsor Team', home_show_team_path %>
<button>Sponsor Players</button>
<div>
    <div>
        <h2>Description</h2>
        <p>descriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescriptiondescription</p>
    </div>
    <div>
        <h2>Players</h2>
        <div>
            (List of Players)
        </div>
    </div>


</div>

<% if current_user %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to "Login", new_user_session_path %>
<% end %>

WashUSoccerFundraiser/app/views/home/show_team.html.erb
<h1>The WashU Team</h1>

<p>Description</p>

<div>
    <h2>Sponsorship Plans:</h2>
    <% @Plans.each do |plan| %>
        <div>
            <h3><%= plan.name %></h3>
            <p><%= plan.description %></p>
            <p>Price: $<%= sprintf("%.2f", (plan.price_cents / 100.0)) %></p>
            <%= button_to 'Sponsor', checkout_create_path, method: :post, remote:true, params: {id: plan.id} %>
        </div>
    <% end %>
</div>

<%= link_to 'Back', root_path %>

WashUSoccerFundraiser/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WashUSoccerFundraiser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

WashUSoccerFundraiser/app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price_cents %>
    <%= form.number_field :price_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

WashUSoccerFundraiser/app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

WashUSoccerFundraiser/app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.name %></td>
        <td><%= plan.description %></td>
        <td><%= plan.price_cents %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

WashUSoccerFundraiser/app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Back', plans_path %>

WashUSoccerFundraiser/app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plan.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>

<p>
  <strong>Price cents:</strong>
  <%= @plan.price_cents %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>